### PR TITLE
updated the pic in README.md

### PR DESCRIPTION
**Pull request by soumam007**
shot1
Issue no #41

### CODE REVIEW

**Comment by thealphadollar** [comment]
Wait, take another one with the window saying "Air Hockey"

**Comment by thealphadollar** [comment]
I'm putting PR for that.

**Comment by Aniq55** [comment]
@soumam007

**Comment by Aniq55** [comment]
sync your fork and run again. you'll understand @soumam007

**Comment by soumam007** [comment]
i am closing this one since i made the PR from a new branch

**Pull request closed without merging**
