### PR TITLE
Added color and mode selection using keyboard

### PR DESCRIPTION
**Pull request by ghost**
Can move the selection box left and right using keyboard but code hangs up while selecting EASY or HARD mode

### CODE REVIEW

**Comment by Aniq55** [comment]
Remove the easy hard selection part then, so that no error occurs. Then this PR can be merged.

**Comment by ghost** [comment]
Done,sir

**Comment by Aniq55** [comment]
@kishore-saldanha, it still has merge conflicts

**Comment by ghost** [comment]
I was working on an older version of code . Please check  Pull request #154
. https://github.com/NITDgpOS/AirHockey/pull/154

**Pull request closed without merging**
