### PR TITLE
#125 solved

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Aniq55** [comment]
@thealphadollar @nityanandagohain could you please review this?

**Review by thealphadollar — CHANGES_REQUESTED** [review]
@kishore-saldanha 
1. Please check for the unnecessary white spaces here and there which have led to the entire code being added to your contribution count.
(https://github.com/Microsoft/vscode/issues/32226, https://stackoverflow.com/questions/11452675/git-diff-shows-the-same-line-as-both-deleted-and-added)
2. No need to add that int along with drawing circle.
3. Instead of storing key press values, which will lead to key ghosting (one key entry while many keys pressed), apply the update changes within the if condition.
4. Some other minor changes here and there which you'll get after reviewing your code before commiting.

**Comment by ghost** [comment]
Alright . Is it possible to fork again from the main repository or do I
have to work on my forked branch .

**Comment by thealphadollar** [comment]
@kishore-saldanha I'll recommend, make a new fork after deleting your old one. Do locally save the changes you made, so it's easier to compare and rewrite.

**Comment by ghost** [comment]
So I followed your advice and put all key presses together in one event
loop. The keys 'a' and 'd' work fine but when I select the mode easy using
'e' key the code seems to hang up in collidesWithPaddle function in puck.py
. Any clue what is happening?

**Comment by nityanandagohain** [comment]
@kishore-saldanha you can give screen shots of your code and problem in gitter .

**Comment by thealphadollar** [comment]
Please close the PR.

**Pull request closed without merging**
