### PR TITLE
Directory changes

### LINKED ISSUE #85: Directory changes
* Rename `img` to `aux` (for auxiliary) and put the `1.wav` file inside it
* Make the necessary changes in the README and python files

### PR DESCRIPTION
**Pull request by Lasers67**
fix #85

### CODE REVIEW

**Comment by Aniq55** [comment]
Please make the changes in the README too @Lasers67

**Comment by Lasers67** [comment]
What all changes in the readme are to be done? There seems no reference to img folder

**Comment by Aniq55** [comment]
This part @Lasers67 
```
## Screenshots

>StartScreen
![StartScreen](/img/Shot1.png)

>Gameplay
![Gameplay](/img/Shot2.png)
```

**Comment by Aniq55** [comment]
@Lasers67 why all your PRs have another account of yours involved?

**Comment by Lasers67** [comment]
Thats also my account, i am unable to push it to my repo by terminal.

**Pull request merged**
