### PR TITLE
Improved collision detection between puck and paddle

### PR DESCRIPTION
**Pull request by CaptainDaVinci**
Earlier the collision detection was between rectangles. Two circles collide if the distance between their centers is less than or equal to the sum of the radius of the circles. 

Removed redundant code in rendering of paddles.

### CODE REVIEW

**Comment by Aniq55** [comment]
Which issue are you addressing? #50  ? @CaptainDaVinci

**Comment by CaptainDaVinci** [comment]
Yes, #50

**Comment by Aniq55** [comment]
Nice work @CaptainDaVinci (:

**Comment by CaptainDaVinci** [comment]
Thanks :)

**Pull request merged**
