### PR TITLE
Play sound each time a paddle strikes the puck 

### LINKED ISSUE #10: Play sound each time a paddle strikes the puck

### PR DESCRIPTION
**Pull request by Lasers67**

### CODE REVIEW

**Comment by Aniq55** [comment]
@Lasers67 include the issue heading as the PR heading and Fixes #issue_number as the PR body.

**Comment by Aniq55** [comment]
Have you increased the puck and paddle size again?

**Comment by Lasers67** [comment]
No, it is in accordance with the master branch itself 
This commit was to give sound on contact with puck

**Comment by Aniq55** [comment]
why is the `constants.py` file included then?

**Comment by Lasers67** [comment]
The constants are same as in the master branch and my commit isnt that so?

**Comment by Aniq55** [comment]
yes, I see that. But why does it show it as a change? I see the only logical change is the addition of music. so the PR is mergeable. RENAME THE PR @Lasers67

**Comment by Lasers67** [comment]
Done :)

**Comment by Lasers67** [comment]
fix #10

**Pull request merged**
